import ColorConversion as cc
import mss
import Data

PIXEL_PLAYER_X_COORD = (8, 25)
PIXEL_PLAYER_Y_COORD = (13, 25)
PIXEL_PLAYER_FACING = (18, 25)
PIXEL_ZONE_FIRSTNAME = (23, 25)
PIXEL_ZONE_SECONDNAME = (28, 25)
PIXEL_PLAYER_CORPSE_X_COORD = (33, 25)
PIXEL_PLAYER_CORPSE_Y_COORD = (38, 25)
PIXEL_PLAYER_BOOLEAN_VAR = (43, 25)
PIXEL_PLAYER_HEALTH_MAX = (55, 25)
PIXEL_PLAYER_HEALTH_CURR = (58, 25)
PIXEL_PLAYER_MANA_MAX = (63, 25)
PIXEL_PLAYER_MANA_CURR = (68, 25)
PIXEL_PLAYER_LEVEL = (73, 25)
PIXEL_PLAYER_RANGE = (78, 25)
PIXEL_TARGET_NAMEFIRST = (83, 25)
PIXEL_TARGET_NAMESECOND = (88, 25)
PIXEL_TARGET_HEALTH_MAX = (93, 25)
PIXEL_TARGET_HEALTH_CURR = (98, 25)
PIXEL_IS_LOOTING_BOP = (1280+90, 720+270)
PIXEL_IS_LOOTING_BOE = (120, 200)


def thread_monitor(threadname):
    sct = mss.mss()
    while True:
        scr2 = sct.grab({"mon": 2, "top": 0,"left": 0, "width": 300, "height": 30})
        Data.PLAYER_X_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_X_COORD))
        Data.PLAYER_Y_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_Y_COORD))
        Data.PLAYER_FACING = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_FACING))
        Data.ZONE_FIRSTNAME = cc.ColorToString(*scr2.pixel(*PIXEL_ZONE_FIRSTNAME))
        Data.ZONE_SECONDNAME = cc.ColorToString(*scr2.pixel(*PIXEL_ZONE_SECONDNAME))
        Data.PLAYER_CORPSE_X_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_CORPSE_X_COORD))
        Data.PLAYER_CORPSE_Y_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_CORPSE_Y_COORD))
        Data.PLAYER_BOOLEAN_VAR = cc.ColorToBool(*scr2.pixel(*PIXEL_PLAYER_BOOLEAN_VAR))
        Data.PLAYER_HEALTH_MAX = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_HEALTH_MAX))
        Data.PLAYER_HEALTH_CURR = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_HEALTH_CURR))
        Data.PLAYER_MANA_MAX = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_MANA_MAX))
        Data.PLAYER_MANA_CURR = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_MANA_CURR))
        Data.PLAYER_LEVEL = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_LEVEL))
        Data.PLAYER_RANGE = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_RANGE))
        Data.TARGET_NAMEFIRST = cc.ColorToString(*scr2.pixel(*PIXEL_TARGET_NAMEFIRST))
        Data.TARGET_NAMESECOND = cc.ColorToString(*scr2.pixel(*PIXEL_TARGET_NAMESECOND))
        Data.TARGET_HEALTH_MAX = cc.ColorToInteger(*scr2.pixel(*PIXEL_TARGET_HEALTH_MAX))
        Data.TARGET_HEALTH_CURR = cc.ColorToInteger(*scr2.pixel(*PIXEL_TARGET_HEALTH_CURR))
        Data.TARGET_IN_COMBAT, Data.TARGET_IS_DEAD, Data.PLAYER_IS_DEAD, Data.PLAYER_NUM_FREE_TALENT_POINTS, Data.PLAYER_NEEDS_TO_BUY_WATER, Data.PLAYER_HAS_FOOD_BUFF, Data.PLAYER_COMBO_POINTS, \
        Data.PLAYER_IN_STEALTH, Data.PLAYER_ICE_BARRIER, Data.PLAYER_HAS_BROKEN_EQUIPMENT, Data.PLAYER_IN_FLIGHT, Data.PLAYER_NEEDS_TO_BUY_FOOD, \
        Data.PLAYER_CASTING_SPELL, Data.PLAYER_HAS_DRINK_BUFF, Data.PLAYER_IN_COMBAT, Data.TARGET_ATTACKING_PLAYER, Data.PLAYER_CHANNELING_SPELL, Data.PROCESS_EXIT_STATUS = cc.ColorToBool(*scr2.pixel(*PIXEL_PLAYER_BOOLEAN_VAR))
        #... add more