import ColorConversion as cc
import mss
import Data

PIXEL_PLAYER_X_COORD = (8, 25)
PIXEL_PLAYER_Y_COORD = (13, 25)
PIXEL_PLAYER_FACING = (18, 25)
PIXEL_ZONE_FIRSTNAME = (23, 25)
PIXEL_ZONE_SECONDNAME = (28, 25)
PIXEL_PLAYER_CORPSE_X_COORD = (33, 25)
PIXEL_PLAYER_CORPSE_Y_COORD = (38, 25)
PIXEL_PLAYER_BOOLEAN_VAR = (43, 25)
PIXEL_PLAYER_HEALTH_MAX = (55, 25)
PIXEL_PLAYER_HEALTH_CURR = (58, 25)
PIXEL_PLAYER_MANA_MAX = (63, 25)
PIXEL_PLAYER_MANA_CURR = (68, 25)
PIXEL_PLAYER_LEVEL = (73, 25)
PIXEL_PLAYER_RANGE = (78, 25)
PIXEL_TARGET_NAMEFIRST = (83, 25)
PIXEL_TARGET_NAMESECOND = (88, 25)
PIXEL_TARGET_HEALTH_MAX = (93, 25)
PIXEL_TARGET_HEALTH_CURR = (98, 25)
PIXEL_IS_LOOTING_BOP = (1280+90, 720+270)
PIXEL_IS_LOOTING_BOE = (120, 200)


def thread_monitor(threadname):
    sct = mss.mss()
    # global PLAYER_X_COORD
    # global PLAYER_Y_COORD
    # global PLAYER_FACING
    # global ZONE_FIRSTNAME
    # global ZONE_SECONDNAME
    # global PLAYER_CORPSE_X_COORD
    # global PLAYER_CORPSE_Y_COORD
    # global PLAYER_BOOLEAN_VAR
    # global PLAYER_HEALTH_MAX
    # global PLAYER_HEALTH_CURR
    # global PLAYER_MANA_MAX
    # global PLAYER_MANA_CURR
    # global PLAYER_LEVEL
    # global PLAYER_RANGE
    # global TARGET_NAMEFIRST
    # global TARGET_NAMESECOND
    # global TARGET_HEALTH_MAX
    # global TARGET_HEALTH_CURR
    # global TARGET_IN_COMBAT
    # global TARGET_IS_ENEMY
    # global PLAYER_IS_DEAD
    # global PLAYER_FREE_TALENT_POINTS
    # global PLAYER_NEED_WATER
    # global PLAYER_HAS_FOOD_BUFF
    # global PLAYER_IN_FLIGHT
    # global PLAYER_EATING
    # global PLAYER_IN_COMBAT
    # global TARGET_ATTACKING_PLAYER
    # global TARGET_IN_COMBAT, TARGET_IS_DEAD, PLAYER_IS_DEAD, PLAYER_NUM_FREE_TALENT_POINTS, PLAYER_NEEDS_TO_BUY_WATER, PLAYER_HAS_FOOD_BUFF, PLAYER_COMBO_POINTS, \
    # PLAYER_IN_STEALTH, PLAYER_ICE_BARRIER, PLAYER_HAS_BROKEN_EQUIPMENT, PLAYER_IN_FLIGHT, PLAYER_NEEDS_TO_BUY_FOOD, \
    # PLAYER_EVOCATION, PLAYER_HAS_DRINK_BUFF, PLAYER_IN_COMBAT, TARGET_ATTACKING_PLAYER, PLAYER_NEEDS_MANAGEM, PROCESS_EXIT_STATUS
    while True:
        scr2 = sct.grab({"mon": 2, "top": 0,"left": 0, "width": 300, "height": 30})
        Data.PLAYER_X_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_X_COORD))
        Data.PLAYER_Y_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_Y_COORD))
        Data.PLAYER_FACING = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_FACING))
        Data.ZONE_FIRSTNAME = cc.ColorToString(*scr2.pixel(*PIXEL_ZONE_FIRSTNAME))
        Data.ZONE_SECONDNAME = cc.ColorToString(*scr2.pixel(*PIXEL_ZONE_SECONDNAME))
        Data.PLAYER_CORPSE_X_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_CORPSE_X_COORD))
        Data.PLAYER_CORPSE_Y_COORD = cc.ColorToDecimal(*scr2.pixel(*PIXEL_PLAYER_CORPSE_Y_COORD))
        Data.PLAYER_BOOLEAN_VAR = cc.ColorToBool(*scr2.pixel(*PIXEL_PLAYER_BOOLEAN_VAR))
        Data.PLAYER_HEALTH_MAX = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_HEALTH_MAX))
        Data.PLAYER_HEALTH_CURR = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_HEALTH_CURR))
        Data.PLAYER_MANA_MAX = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_MANA_MAX))
        Data.PLAYER_MANA_CURR = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_MANA_CURR))
        Data.PLAYER_LEVEL = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_LEVEL))
        Data.PLAYER_RANGE = cc.ColorToInteger(*scr2.pixel(*PIXEL_PLAYER_RANGE))
        Data.TARGET_NAMEFIRST = cc.ColorToString(*scr2.pixel(*PIXEL_TARGET_NAMEFIRST))
        Data.TARGET_NAMESECOND = cc.ColorToString(*scr2.pixel(*PIXEL_TARGET_NAMESECOND))
        Data.TARGET_HEALTH_MAX = cc.ColorToInteger(*scr2.pixel(*PIXEL_TARGET_HEALTH_MAX))
        Data.TARGET_HEALTH_CURR = cc.ColorToInteger(*scr2.pixel(*PIXEL_TARGET_HEALTH_CURR))
        Data.TARGET_IN_COMBAT, Data.TARGET_IS_DEAD, Data.PLAYER_IS_DEAD, Data.PLAYER_NUM_FREE_TALENT_POINTS, Data.PLAYER_NEEDS_TO_BUY_WATER, Data.PLAYER_HAS_FOOD_BUFF, Data.PLAYER_COMBO_POINTS, \
        Data.PLAYER_IN_STEALTH, Data.PLAYER_ICE_BARRIER, Data.PLAYER_HAS_BROKEN_EQUIPMENT, Data.PLAYER_IN_FLIGHT, Data.PLAYER_NEEDS_TO_BUY_FOOD, \
        Data.PLAYER_EVOCATION, Data.PLAYER_HAS_DRINK_BUFF, Data.PLAYER_IN_COMBAT, Data.TARGET_ATTACKING_PLAYER, Data.PLAYER_NEEDS_MANAGEM, Data.PROCESS_EXIT_STATUS = cc.ColorToBool(*scr2.pixel(*PIXEL_PLAYER_BOOLEAN_VAR))
        #... add more